### ISSUE TITLE
"Requires authentication (401)" errors when accessing github

### ISSUE THREAD

**Issue by robinpaulson** [slapperwan/gh4a#240]
Whenever I access anything through Octodroid/gh4a, a toast appears on screen with the above error. I am logged in to my account. I also cannot post comments on issues, and periodically receive messages suggesting my IP address has been rate limited due to non-authentication.

Replicant 4.2 (a fork of android - www.replicant.us)
Octodroid 3.7.1 installed via F-Droid
Samsung Galaxy S2

**Comment by maniac103** [comment]
I wonder whether your token has expired. Did you try logging out and logging in again afterwards?

**Comment by robinpaulson** [comment]
I only installed gh4a/Octodroid yesterday. After it failed I did log out and then back in. The "github" application works fine, but it's rather poor compared to octodroid.

**Comment by mikeroll** [comment]
Affects me too. Tried logging out and back in, even tried reinstalling the app.

**Comment by maniac103** [comment]
I vaguely remember a problem like that and think we fixed that, but can't find the commit at the moment :-(
Can you please try the version built from the material-theme branch? It can be found here: https://drone.io/github.com/slapperwan/gh4a/files/build/outputs/apk/gh4a-debug.apk

(@slapperwan We really, really ought to release this as 3.8...)

**Comment by robinpaulson** [comment]
I tried the apk from the link above, I still get the same errors.

From alogcat, the error messages are:
I( 2188: 2200) Start proc com.github.mobile:auth for service com.github.mobile/.accounts.AccountAuthenticatorService: pid=3729 uid=10086 gids={50086, 3003, 1028}
E( 3729: 3741) 	at com.github.mobile.accounts.AccountAuthenticator.createAuthorization(AccountAuthenticator.java:143)
E( 3729: 3741) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:173)
E( 3729: 3741) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3741) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthorization(AccountAuthenticator.java:125)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:171)
E( 3729: 3740) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3740) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.createAuthorization(AccountAuthenticator.java:143)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:173)
E( 3729: 3740) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3740) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E( 3659: 3816) Requires authentication (401)
E( 3659: 3816) org.eclipse.egit.github.core.client.NoSuchPageException: Requires authentication (401)
E( 3659: 3816) Caused by: org.eclipse.egit.github.core.client.RequestException: Requires authentication (401)
E( 3659: 3818) Requires authentication (401)
E( 3659: 3818) org.eclipse.egit.github.core.client.RequestException: Requires authentication (401)
E( 3659: 3814) Requires authentication (401)
E( 3659: 3814) org.eclipse.egit.github.core.client.RequestException: Requires authentication (401)
E( 3729: 3741) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthorization(AccountAuthenticator.java:125)
E( 3729: 3741) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:171)
E( 3729: 3741) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3741) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.createAuthorization(AccountAuthenticator.java:143)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:173)
E( 3729: 3740) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3740) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthorization(AccountAuthenticator.java:125)
E( 3729: 3740) 	at com.github.mobile.accounts.AccountAuthenticator.getAuthToken(AccountAuthenticator.java:171)
E( 3729: 3740) 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:196)
E( 3729: 3740) 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:113)

**Comment by Wedmer** [comment]
Just delete old token for gh4a at github settings->personal access tokens

**Comment by robinpaulson** [comment]
Excellent, working now

**Comment by maniac103** [comment]
Interesting. Gh4a re-uses existing authorizations (as does Github's official app), so that explains things.
It looks like this is due to a server side API change ([1]), I'll look into it.

[1] https://developer.github.com/v3/oauth_authorizations/#deprecation-notice

**Comment by maniac103** [comment]
See commit https://github.com/slapperwan/gh4a/commit/7d7125642df08e94e8400dd7b8d835f482588db3

**Comment by robinpaulson** [comment]
Excellent, glad to see this fixed.

Could you tag this as an incremental update, say to 3.7.2? Then we could get the updated version into F-Droid straight away? Cheers.
